
trigger:
- main

resources:
- repo: self

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/src/Dockerfile'
  webRepository: 'web'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and publish Java container
  jobs:  
  - job: Build
    displayName: Build

    pool:
      vmImage: $(vmImageName)
    variables:
    - group: Release
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'
        options: '-DskipITs --settings ./maven/settings.xml'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
      
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          target/myshuttledev*.war
          *.sql
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
      
    - task: Docker@2
      inputs:
        containerRegistry: 'acrconnection'
        repository: '$(webRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(Build.ArtifactStagingDirectory)'
        tags: |
            $(tag)
    
    - task: AzureMysqlDeployment@1
      inputs:
        azureSubscription: 'Java Connection'
        ServerName: '$(MySqlServer).mysql.database.azure.com'
        DatabaseName: 'alm'
        SqlUsername: '$(MySqlUserName)@$(MySqlServer)'
        SqlPassword: '$(MySqlPassword)'
        TaskNameSelector: 'SqlTaskFile'
        SqlFile: '$(Build.SourcesDirectory)/CreateMYSQLDB.sql'
        IpDetectionMethod: 'AutoDetect'
      
- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: $(vmImageName)
    environment: java-container
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
    
          - task: AzureWebAppContainer@1
            inputs:
              azureSubscription: 'Java Connection'
              appName: '$(WebAppName)'
              containers: '$(RegistryName)/$(webRepository):$(build.buildId)'
              
          - task: AzureAppServiceSettings@1
            inputs:
              azureSubscription: 'Java Connection'
              appName: '$(WebAppName)'
              resourceGroupName: 'java-containers-cicd-rg'
              connectionStrings: |
                [
                  {
                    "name": "MyShuttleDb",
                    "value": "jdbc:mysql://$(MySqlServer).mysql.database.azure.com:3306/alm?useSSL=true&requireSSL=false&autoReconnect=true&user=$(MySqlUserName)@$(MySqlServer)&password=$(MySqlPassword)",
                    "type": "MySql",
                    "slotSetting": false
                  }
                ]